export const UPDATE_DATA = "room/UPDATE_DATE"
export const UPDATE_SOCKET_MESSAGES = "room/UPDATE_SOCKET_MESSAGES"
export const DELETE_MESSAGE = "room/DELETE_MESSAGE"
export const UPDATE_MESSAGE = 'room/UPDATE_MESSAGE'